# -*- coding: utf-8 -*-
"""chinoV2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZEByeOQKmgCP3-OQg_UmRPAjIPt2322e
"""

"""
config.py
Configuración global del proyecto OCR para caracteres chinos manuscritos.
"""

from pathlib import Path
import tensorflow as tf

# ==========================================================
# RUTAS
# ==========================================================

PROJECT_ROOT = Path.cwd()

DATASET_DIR = PROJECT_ROOT / "dataset"

FONTS_DIR = DATASET_DIR / "fonts"

IMAGES_DIR = DATASET_DIR / "images"

OUTPUT_DIR = PROJECT_ROOT / "outputs"

CHECKPOINT_DIR = PROJECT_ROOT / "checkpoints"

LOG_DIR = PROJECT_ROOT / "logs"

HISTORY_DIR = PROJECT_ROOT / "history"

# Crear directorios automáticamente

for folder in [

    DATASET_DIR,

    FONTS_DIR,

    IMAGES_DIR,

    OUTPUT_DIR,

    CHECKPOINT_DIR,

    LOG_DIR,

    HISTORY_DIR,

]:
    folder.mkdir(parents=True, exist_ok=True)

# ==========================================================
# IMAGEN
# ==========================================================

# Subimos a 128 para conservar mejor los trazos

IMAGE_SIZE = (128, 128)

CHANNELS = 1

BACKGROUND_COLOR = 255

FOREGROUND_COLOR = 0

# ==========================================================
# DATASET
# ==========================================================

# Cantidad de imágenes BASE por fuente
# La augmentación generará miles de variantes adicionales

IMAGES_PER_FONT = 20

TRAIN_SPLIT = 0.80

VALIDATION_SPLIT = 0.20

RANDOM_SEED = 42

# ==========================================================
# ENTRENAMIENTO
# ==========================================================

BATCH_SIZE = 32

INITIAL_EPOCHS = 15

FINE_TUNE_EPOCHS = 15

INITIAL_LEARNING_RATE = 1e-3

FINE_TUNE_LEARNING_RATE = 1e-5

# ==========================================================
# MODELO
# ==========================================================

PRIMARY_BACKBONE = "EfficientNetV2B0"

FALLBACK_BACKBONE = "MobileNetV3Small"

USE_IMAGENET_WEIGHTS = True

DROPOUT_RATE = 0.35

# ==========================================================
# EXPORTACIÓN
# ==========================================================

MODEL_FILENAME = "model.keras"

LABELS_FILENAME = "labels.json"

METADATA_FILENAME = "metadata.json"

HISTORY_FILENAME = "history.json"

# ==========================================================
# TF.DATA
# ==========================================================

AUTOTUNE = tf.data.AUTOTUNE

# ==========================================================
# FUENTES
# ==========================================================

# Queremos llegar aproximadamente a 15–20 fuentes

MIN_FONTS = 12

TARGET_FONTS = 20

# ==========================================================
# AUGMENTACIÓN
# ==========================================================

MAX_ROTATION = 10

MAX_TRANSLATION = 6

MIN_SCALE = 0.90

MAX_SCALE = 1.10

GAUSSIAN_NOISE_STD = 8

GAUSSIAN_BLUR_KERNEL = 3

PERSPECTIVE_DISTORTION = 4

# ==========================================================
# INFORMACIÓN
# ==========================================================

VERSION = "2.0"

PROJECT_NAME = "Chinese Handwritten OCR"

# ==========================================================
# UTILIDAD
# ==========================================================

def print_config():

    print("=" * 60)
    print(PROJECT_NAME)
    print(f"Versión : {VERSION}")
    print("=" * 60)

    print(f"Imagen              : {IMAGE_SIZE}")
    print(f"Batch               : {BATCH_SIZE}")
    print(f"Epochs Iniciales    : {INITIAL_EPOCHS}")
    print(f"Fine Tune Epochs    : {FINE_TUNE_EPOCHS}")
    print(f"Learning Rate       : {INITIAL_LEARNING_RATE}")
    print(f"Fine Tune LR        : {FINE_TUNE_LEARNING_RATE}")
    print(f"Backbone Principal  : {PRIMARY_BACKBONE}")
    print(f"Backbone Alterno    : {FALLBACK_BACKBONE}")
    print(f"Imágenes/Fuente     : {IMAGES_PER_FONT}")
    print(f"Fuentes Objetivo    : {TARGET_FONTS}")
    print("=" * 60)

# ==========================================================
# TEST
# ==========================================================

if __name__ == "__main__":

    print_config()

    print("\nDirectorios creados correctamente.\n")

# ==========================================================
# MÓDULO 2
# Registro de caracteres
# ==========================================================

from dataclasses import dataclass, asdict
import json

# ==========================================================
# Clase
# ==========================================================

@dataclass
class ChineseCharacter:

    hanzi: str
    pinyin: str
    spanish: str
    category: str


# ==========================================================
# Base de datos
# ==========================================================

CHARACTERS = [

    # ---------------- Animales ----------------

    ChineseCharacter("猫","māo","gato","Animales"),
    ChineseCharacter("狗","gǒu","perro","Animales"),
    ChineseCharacter("鸟","niǎo","pájaro","Animales"),
    ChineseCharacter("鱼","yú","pez","Animales"),
    ChineseCharacter("马","mǎ","caballo","Animales"),
    ChineseCharacter("牛","niú","vaca","Animales"),
    ChineseCharacter("羊","yáng","oveja","Animales"),
    ChineseCharacter("猪","zhū","cerdo","Animales"),
    ChineseCharacter("虎","hǔ","tigre","Animales"),
    ChineseCharacter("兔","tù","conejo","Animales"),

    # ---------------- Profesiones ----------------

    ChineseCharacter("医","yī","médico","Profesiones"),
    ChineseCharacter("师","shī","maestro","Profesiones"),
    ChineseCharacter("警","jǐng","policía","Profesiones"),
    ChineseCharacter("厨","chú","cocinero","Profesiones"),
    ChineseCharacter("工","gōng","obrero","Profesiones"),
    ChineseCharacter("农","nóng","agricultor","Profesiones"),
    ChineseCharacter("画","huà","pintor","Profesiones"),
    ChineseCharacter("员","yuán","empleado","Profesiones"),

    # ---------------- Edificios ----------------

    ChineseCharacter("家","jiā","casa","Edificios"),
    ChineseCharacter("校","xiào","escuela","Edificios"),
    ChineseCharacter("店","diàn","tienda","Edificios"),
    ChineseCharacter("院","yuàn","hospital","Edificios"),
    ChineseCharacter("馆","guǎn","edificio","Edificios"),
    ChineseCharacter("楼","lóu","edificio alto","Edificios"),
    ChineseCharacter("桥","qiáo","puente","Edificios"),

    # ---------------- Naturaleza ----------------

    ChineseCharacter("山","shān","montaña","Naturaleza"),
    ChineseCharacter("水","shuǐ","agua","Naturaleza"),
    ChineseCharacter("火","huǒ","fuego","Naturaleza"),
    ChineseCharacter("木","mù","árbol","Naturaleza"),
    ChineseCharacter("土","tǔ","tierra","Naturaleza"),
    ChineseCharacter("风","fēng","viento","Naturaleza"),
    ChineseCharacter("雨","yǔ","lluvia","Naturaleza"),
    ChineseCharacter("云","yún","nube","Naturaleza"),

    # ---------------- Objetos ----------------

    ChineseCharacter("书","shū","libro","Objetos"),
    ChineseCharacter("门","mén","puerta","Objetos"),
    ChineseCharacter("车","chē","automóvil","Objetos"),
    ChineseCharacter("桌","zhuō","mesa","Objetos"),
    ChineseCharacter("椅","yǐ","silla","Objetos"),
    ChineseCharacter("笔","bǐ","lápiz","Objetos"),
    ChineseCharacter("杯","bēi","vaso","Objetos"),
    ChineseCharacter("伞","sǎn","paraguas","Objetos"),
    ChineseCharacter("钟","zhōng","reloj","Objetos"),

    # ---------------- Familia ----------------

    ChineseCharacter("人","rén","persona","Familia"),
    ChineseCharacter("男","nán","hombre","Familia"),
    ChineseCharacter("女","nǚ","mujer","Familia"),
    ChineseCharacter("父","fù","padre","Familia"),
    ChineseCharacter("母","mǔ","madre","Familia"),
    ChineseCharacter("子","zǐ","hijo","Familia"),
    ChineseCharacter("兄","xiōng","hermano mayor","Familia"),
    ChineseCharacter("姐","jiě","hermana mayor","Familia"),

]

# ==========================================================
# Validación
# ==========================================================

hanzi_list = [c.hanzi for c in CHARACTERS]

assert len(hanzi_list) == len(set(hanzi_list)), \
    "Hay caracteres duplicados."

# ==========================================================
# Índices
# ==========================================================

CHAR_TO_INDEX = {
    c.hanzi: i
    for i, c in enumerate(CHARACTERS)
}

INDEX_TO_CHAR = {
    i: c
    for i, c in enumerate(CHARACTERS)
}

LABELS = [
    c.hanzi
    for c in CHARACTERS
]

NUM_CLASSES = len(CHARACTERS)

# ==========================================================
# Exportar labels.json
# ==========================================================

with open(
    OUTPUT_DIR / LABELS_FILENAME,
    "w",
    encoding="utf8"
) as f:

    json.dump(
        LABELS,
        f,
        indent=4,
        ensure_ascii=False
    )

# ==========================================================
# Exportar metadata.json
# ==========================================================

metadata = []

for idx, char in enumerate(CHARACTERS):

    metadata.append({

        "index": idx,

        "hanzi": char.hanzi,

        "pinyin": char.pinyin,

        "spanish": char.spanish,

        "category": char.category

    })

with open(
    OUTPUT_DIR / METADATA_FILENAME,
    "w",
    encoding="utf8"
) as f:

    json.dump(
        metadata,
        f,
        indent=4,
        ensure_ascii=False
    )

# ==========================================================
# Resumen
# ==========================================================

print("="*60)

print("REGISTRO DE CARACTERES")

print("="*60)

print(f"Total de clases : {NUM_CLASSES}")

print(f"Primer carácter : {CHARACTERS[0]}")

print(f"Último carácter : {CHARACTERS[-1]}")

print()

print("✔ labels.json generado")

print("✔ metadata.json generado")

print("✔ Registro cargado correctamente")

print("="*60)

# ==========================================================
# MÓDULO 3
# Descarga automática de fuentes chinas
# ==========================================================

import os
import requests
from pathlib import Path
from PIL import ImageFont
from tqdm.auto import tqdm

# ==========================================================
# Dependencias
# ==========================================================

try:
    import requests
except ImportError:
    !pip -q install requests
    import requests

try:
    from tqdm.auto import tqdm
except ImportError:
    !pip -q install tqdm
    from tqdm.auto import tqdm

# ==========================================================
# Configuración
# ==========================================================

FONTS_DIR.mkdir(parents=True, exist_ok=True)

# Repositorios oficiales
REPOSITORIES = [

    (
        "googlefonts",
        "noto-cjk",
        "Sans/OTF/SimplifiedChinese"
    ),

    (
        "adobe-fonts",
        "source-han-sans",
        "SubsetOTF/CN"
    )

]

# ==========================================================
# Descargar lista de fuentes
# ==========================================================

def github_directory(owner, repo, path):

    url = f"https://api.github.com/repos/{owner}/{repo}/contents/{path}"

    response = requests.get(url)

    if response.status_code != 200:

        print(f"No fue posible acceder a {repo}")

        return []

    return response.json()


# ==========================================================
# Descargar archivo
# ==========================================================

def download_file(url, destination):

    if destination.exists():
        return

    r = requests.get(url, stream=True)

    r.raise_for_status()

    with open(destination, "wb") as f:

        for chunk in r.iter_content(8192):

            if chunk:

                f.write(chunk)


# ==========================================================
# Descarga
# ==========================================================

downloaded = 0

print("=" * 60)
print("DESCARGANDO FUENTES")
print("=" * 60)

for owner, repo, path in REPOSITORIES:

    files = github_directory(owner, repo, path)

    if not files:
        continue

    print(f"\nRepositorio: {repo}")

    for file in tqdm(files):

        name = file["name"]

        if not (
            name.endswith(".otf")
            or
            name.endswith(".ttf")
        ):
            continue

        destination = FONTS_DIR / name

        download_file(

            file["download_url"],

            destination

        )

        downloaded += 1

print()

print(f"Descargadas: {downloaded}")

# ==========================================================
# Validación
# ==========================================================

AVAILABLE_FONTS = []

INVALID_FONTS = []

for font in sorted(FONTS_DIR.iterdir()):

    if font.suffix.lower() not in (".ttf", ".otf"):
        continue

    try:

        ImageFont.truetype(

            str(font),

            64

        )

        AVAILABLE_FONTS.append(font)

    except Exception:

        INVALID_FONTS.append(font)

# ==========================================================
# Resumen
# ==========================================================

print()

print("=" * 60)
print("RESUMEN")
print("=" * 60)

print(f"Fuentes válidas   : {len(AVAILABLE_FONTS)}")

print(f"Fuentes inválidas : {len(INVALID_FONTS)}")

print()

if AVAILABLE_FONTS:

    print("Primeras fuentes:")

    for font in AVAILABLE_FONTS[:10]:

        print(" •", font.name)

print()

print("✔ AVAILABLE_FONTS creada")

print("=" * 60)

# ==========================================================
# MÓDULO 4
# Renderizador profesional V2
# Compatible con Google Colab
# ==========================================================

import random
import numpy as np

from PIL import (
    Image,
    ImageDraw,
    ImageFont
)

# ==========================================================
# Configuración
# ==========================================================

START_FONT_SIZE = 110

MIN_FONT_SIZE = 55

SAFE_MARGIN = 12

MAX_OFFSET = 3

# ==========================================================
# Fuente aleatoria
# ==========================================================

def random_font(size):

    font_path = random.choice(AVAILABLE_FONTS)

    return ImageFont.truetype(
        str(font_path),
        size=size
    )

# ==========================================================
# Encontrar tamaño adecuado
# ==========================================================

def fit_font(draw, hanzi):

    size = START_FONT_SIZE

    while size >= MIN_FONT_SIZE:

        font = random_font(size)

        bbox = draw.textbbox(
            (0,0),
            hanzi,
            font=font
        )

        left, top, right, bottom = bbox

        width = right-left
        height = bottom-top

        if (
            width <= IMAGE_SIZE[0]-SAFE_MARGIN*2
            and
            height <= IMAGE_SIZE[1]-SAFE_MARGIN*2
        ):

            return font, bbox

        size -= 2

    raise RuntimeError(
        "No fue posible ajustar el carácter."
    )

# ==========================================================
# Render
# ==========================================================

def render_character(hanzi):

    image = Image.new(

        "L",

        IMAGE_SIZE,

        BACKGROUND_COLOR

    )

    draw = ImageDraw.Draw(image)

    font, bbox = fit_font(

        draw,

        hanzi

    )

    left, top, right, bottom = bbox

    width = right-left
    height = bottom-top

    # ======================================================
    # Centro exacto
    # ======================================================

    x = (IMAGE_SIZE[0]-width)/2-left

    y = (IMAGE_SIZE[1]-height)/2-top

    # ======================================================
    # Variación pequeña
    # ======================================================

    x += random.randint(
        -MAX_OFFSET,
        MAX_OFFSET
    )

    y += random.randint(
        -MAX_OFFSET,
        MAX_OFFSET
    )

    draw.text(

        (x,y),

        hanzi,

        fill=FOREGROUND_COLOR,

        font=font

    )

    return np.array(image)

# ==========================================================
# Test
# ==========================================================

print("="*60)
print("PROBANDO RENDERIZADOR")
print("="*60)

sample = render_character("猫")

print(sample.shape)

print(sample.dtype)

print("OK")

# ==========================================================
# Instalar Albumentations
# ==========================================================

!pip -q install albumentations

# ==========================================================
# MÓDULO 5
# Instalación
# ==========================================================

!pip -q install -U albumentations opencv-python-headless

# ==========================================================
# MÓDULO 5
# Pipeline profesional
# Compatible con Albumentations 2.x
# ==========================================================

import albumentations as A
import numpy as np
import cv2

# ==========================================================
# Pipeline
# ==========================================================

augmentation_pipeline = A.Compose([

    # ------------------------------------------------------
    # Transformaciones geométricas
    # ------------------------------------------------------

    A.Affine(

        scale=(0.92, 1.08),

        translate_percent=(-0.05, 0.05),

        rotate=(-10, 10),

        shear=(-4, 4),

        border_mode=cv2.BORDER_CONSTANT,

        fill=255,

        p=0.90

    ),

    # ------------------------------------------------------

    A.ElasticTransform(

        alpha=20,

        sigma=6,

        p=0.50

    ),

    # ------------------------------------------------------

    A.GridDistortion(

        num_steps=5,

        distort_limit=0.12,

        p=0.40

    ),

    # ------------------------------------------------------

    A.Perspective(

        scale=(0.02,0.05),

        keep_size=True,

        fill=255,

        p=0.35

    ),

    # ------------------------------------------------------
    # Calidad de imagen
    # ------------------------------------------------------

    A.OneOf([

        A.GaussianBlur(

            blur_limit=(3,5),

            p=1

        ),

        A.MedianBlur(

            blur_limit=3,

            p=1

        ),

    ], p=0.30),

    # ------------------------------------------------------

    A.GaussNoise(

        std_range=(0.02,0.05),

        mean_range=(0.0,0.0),

        p=0.40

    ),

    # ------------------------------------------------------

    A.RandomBrightnessContrast(

        brightness_limit=0.10,

        contrast_limit=0.15,

        p=0.50

    ),

])

# ==========================================================
# Función principal
# ==========================================================

def augment(image):

    """
    image : numpy uint8
    """

    result = augmentation_pipeline(

        image=image

    )

    return result["image"]

# ==========================================================
# Prueba
# ==========================================================

sample = render_character("猫")

augmented = augment(sample)

print("="*60)

print("Imagen original")

print(sample.shape)

print(sample.dtype)

print()

print("Imagen aumentada")

print(augmented.shape)

print(augmented.dtype)

print("="*60)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))

plt.subplot(1,2,1)

plt.imshow(sample,cmap="gray")

plt.title("Original")

plt.axis("off")

plt.subplot(1,2,2)

plt.imshow(augmented,cmap="gray")

plt.title("Augmentada")

plt.axis("off")

plt.show()

plt.figure(figsize=(12,12))

for i in range(16):

    plt.subplot(4,4,i+1)

    img = augment(

        render_character("猫")

    )

    plt.imshow(img,cmap="gray")

    plt.axis("off")

plt.tight_layout()

plt.show()

# ==========================================================
# MÓDULO 6
# Generación del dataset
# ==========================================================

import shutil
from pathlib import Path

import cv2
import numpy as np
from tqdm.auto import tqdm

# ==========================================================
# CONFIGURACIÓN
# ==========================================================

# Imágenes por fuente para cada carácter
IMAGES_PER_FONT = 20

# Si True elimina el dataset anterior
RECREATE_DATASET = True

# ==========================================================
# Preparar carpeta
# ==========================================================

if RECREATE_DATASET and IMAGES_DIR.exists():

    shutil.rmtree(IMAGES_DIR)

IMAGES_DIR.mkdir(parents=True, exist_ok=True)

# ==========================================================
# Contador
# ==========================================================

total_images = 0

print("="*60)
print("GENERANDO DATASET")
print("="*60)

# ==========================================================
# Recorrer caracteres
# ==========================================================

for character in tqdm(CHARACTERS):

    class_dir = IMAGES_DIR / character.hanzi

    class_dir.mkdir(exist_ok=True)

    counter = 0

    # ------------------------------------------------------

    for font_path in AVAILABLE_FONTS:

        # Forzar el uso de una fuente concreta
        # reutilizando render_character()

        for _ in range(IMAGES_PER_FONT):

            # Seleccionar temporalmente esta fuente
            old_fonts = AVAILABLE_FONTS
            AVAILABLE_FONTS = [font_path]

            image = render_character(character.hanzi)

            AVAILABLE_FONTS = old_fonts

            image = augment(image)

            filename = class_dir / f"{counter:06}.png"

            cv2.imwrite(
                str(filename),
                image
            )

            counter += 1
            total_images += 1

print()

print("="*60)
print("DATASET GENERADO")
print("="*60)

print(f"Clases           : {NUM_CLASSES}")
print(f"Fuentes          : {len(AVAILABLE_FONTS)}")
print(f"Imágenes/Fuente  : {IMAGES_PER_FONT}")
print(f"Total imágenes   : {total_images}")

print("="*60)

# ==========================================================
# MÓDULO 6.1
# Verificación visual
# ==========================================================

import random
import matplotlib.pyplot as plt

sample_character = random.choice(CHARACTERS)

folder = IMAGES_DIR / sample_character.hanzi

files = list(folder.glob("*.png"))

plt.figure(figsize=(12,12))

for i in range(16):

    img_path = random.choice(files)

    img = cv2.imread(
        str(img_path),
        cv2.IMREAD_GRAYSCALE
    )

    plt.subplot(4,4,i+1)

    plt.imshow(img,cmap="gray")

    plt.axis("off")

plt.suptitle(sample_character.hanzi)

plt.tight_layout()

plt.show()

# ==========================================================
# MÓDULO 7
# DataLoader optimizado para Google Colab
# ==========================================================

import tensorflow as tf

print("=" * 60)
print("CREANDO DATASETS")
print("=" * 60)

# ==========================================================
# Configuración
# ==========================================================

USE_CACHE = False
SHUFFLE_BUFFER = 5000

# ==========================================================
# Dataset entrenamiento
# ==========================================================

train_dataset = tf.keras.utils.image_dataset_from_directory(

    IMAGES_DIR,

    labels="inferred",

    label_mode="int",

    color_mode="grayscale",

    image_size=IMAGE_SIZE,

    batch_size=BATCH_SIZE,

    validation_split=VALIDATION_SPLIT,

    subset="training",

    seed=RANDOM_SEED

)

# IMPORTANTE:
# Guardar los nombres ANTES de aplicar map()
CLASS_NAMES = train_dataset.class_names

# ==========================================================
# Dataset validación
# ==========================================================

validation_dataset = tf.keras.utils.image_dataset_from_directory(

    IMAGES_DIR,

    labels="inferred",

    label_mode="int",

    color_mode="grayscale",

    image_size=IMAGE_SIZE,

    batch_size=BATCH_SIZE,

    validation_split=VALIDATION_SPLIT,

    subset="validation",

    seed=RANDOM_SEED

)

# ==========================================================
# Verificación
# ==========================================================

assert len(CLASS_NAMES) == NUM_CLASSES, (
    f"Se esperaban {NUM_CLASSES} clases "
    f"pero TensorFlow detectó {len(CLASS_NAMES)}."
)

# ==========================================================
# Preprocesamiento
# ==========================================================

def preprocess(images, labels):

    # uint8 -> float32
    images = tf.cast(images, tf.float32) / 255.0

    # Gray -> RGB
    images = tf.image.grayscale_to_rgb(images)

    return images, labels

# ==========================================================
# Pipeline entrenamiento
# ==========================================================

train_dataset = (

    train_dataset

    .shuffle(

        SHUFFLE_BUFFER,

        seed=RANDOM_SEED,

        reshuffle_each_iteration=True

    )

    .map(

        preprocess,

        num_parallel_calls=AUTOTUNE

    )

)

# ==========================================================
# Pipeline validación
# ==========================================================

validation_dataset = (

    validation_dataset

    .map(

        preprocess,

        num_parallel_calls=AUTOTUNE

    )

)

# ==========================================================
# Cache opcional
# ==========================================================

if USE_CACHE:

    train_dataset = train_dataset.cache()

    validation_dataset = validation_dataset.cache()

# ==========================================================
# Prefetch
# ==========================================================

train_dataset = train_dataset.prefetch(AUTOTUNE)

validation_dataset = validation_dataset.prefetch(AUTOTUNE)

# ==========================================================
# Resumen
# ==========================================================

print()

print("=" * 60)
print("DATASETS CREADOS")
print("=" * 60)

print(f"Número de clases : {NUM_CLASSES}")
print(f"Batch size       : {BATCH_SIZE}")
print(f"Resolución       : {IMAGE_SIZE}")

print()

print("Primeras clases:")

for name in CLASS_NAMES[:10]:
    print(" •", name)

print()

print(f"Total clases detectadas : {len(CLASS_NAMES)}")

print()

print("✔ DataLoader preparado correctamente")

print("=" * 60)

# ==========================================================
# MÓDULO 7.1
# Verificación visual
# ==========================================================

import matplotlib.pyplot as plt

images, labels = next(iter(train_dataset))

plt.figure(figsize=(12,12))

for i in range(16):

    plt.subplot(4,4,i+1)

    plt.imshow(images[i])

    plt.title(CLASS_NAMES[int(labels[i])])

    plt.axis("off")

plt.tight_layout()

plt.show()

print()

print("="*60)

print("Batch Shape")

print(images.shape)

print()

print("Labels Shape")

print(labels.shape)

print()

print("✔ DataLoader funcionando correctamente")

print("="*60)

# ==========================================================
# MÓDULO 8
# Construcción del modelo
# ==========================================================

import tensorflow as tf

from tensorflow.keras import layers
from tensorflow.keras import Model

print("=" * 60)
print("CONSTRUYENDO MODELO")
print("=" * 60)

# ==========================================================
# Entrada
# ==========================================================

inputs = layers.Input(

    shape=(

        IMAGE_SIZE[0],

        IMAGE_SIZE[1],

        3

    )

)

# ==========================================================
# Backbone
# ==========================================================

BACKBONE_NAME = "EfficientNetV2B0"

try:

    backbone = tf.keras.applications.EfficientNetV2B0(

        include_top=False,

        weights="imagenet",

        input_tensor=inputs

    )

except Exception:

    BACKBONE_NAME = "MobileNetV3Small"

    backbone = tf.keras.applications.MobileNetV3Small(

        include_top=False,

        weights="imagenet",

        input_tensor=inputs

    )

print()

print("Backbone seleccionado:")

print(BACKBONE_NAME)

# ==========================================================
# Primera fase
# ==========================================================

backbone.trainable = False

# ==========================================================
# Clasificador
# ==========================================================

x = backbone.output

x = layers.GlobalAveragePooling2D()(x)

x = layers.BatchNormalization()(x)

x = layers.Dropout(0.40)(x)

x = layers.Dense(

    512,

    activation="relu"

)(x)

x = layers.Dropout(0.30)(x)

outputs = layers.Dense(

    NUM_CLASSES,

    activation="softmax"

)(x)

model = Model(

    inputs,

    outputs

)

# ==========================================================
# Compilación
# ==========================================================

optimizer = tf.keras.optimizers.Adam(

    learning_rate=1e-3

)

model.compile(

    optimizer=optimizer,

    loss="sparse_categorical_crossentropy",

    metrics=[

        "accuracy"

    ]

)

# ==========================================================
# Resumen
# ==========================================================

print()

print("=" * 60)

print("RESUMEN")

print("=" * 60)

print("Backbone :", BACKBONE_NAME)

print("Clases   :", NUM_CLASSES)

print("LR        :", 1e-3)

print()

model.summary()

print()

print("=" * 60)

print("✔ Modelo construido correctamente")

print("=" * 60)

# ==========================================================
# MÓDULO 9
# Entrenamiento en dos fases
# ==========================================================

import os
import tensorflow as tf

from tensorflow.keras.callbacks import (
    EarlyStopping,
    ReduceLROnPlateau,
    ModelCheckpoint,
    CSVLogger,
    TensorBoard
)

CHECKPOINT_PATH = CHECKPOINT_DIR / "best_model.keras"

LOG_DIR = OUTPUT_DIR / "logs"

LOG_DIR.mkdir(exist_ok=True)

# ==========================================================
# CALLBACKS
# ==========================================================

callbacks = [

    ModelCheckpoint(

        filepath=str(CHECKPOINT_PATH),

        monitor="val_accuracy",

        save_best_only=True,

        verbose=1

    ),

    EarlyStopping(

        monitor="val_loss",

        patience=8,

        restore_best_weights=True,

        verbose=1

    ),

    ReduceLROnPlateau(

        monitor="val_loss",

        factor=0.2,

        patience=4,

        verbose=1

    ),

    CSVLogger(

        str(OUTPUT_DIR / "training_log.csv")

    ),

    TensorBoard(

        log_dir=str(LOG_DIR)

    )

]

# ==========================================================
# FASE 1
# ==========================================================

print("="*60)
print("FASE 1")
print("Entrenando clasificador")
print("="*60)

backbone.trainable = False

model.compile(

    optimizer=tf.keras.optimizers.Adam(

        learning_rate=1e-3

    ),

    loss="sparse_categorical_crossentropy",

    metrics=["accuracy"]

)

history_phase1 = model.fit(

    train_dataset,

    validation_data=validation_dataset,

    epochs=20,

    callbacks=callbacks

)

# ==========================================================
# FASE 2
# ==========================================================

print()
print("="*60)
print("FASE 2")
print("Fine Tuning")
print("="*60)

backbone.trainable = True

# Congelar el 75 %
freeze_until = int(

    len(backbone.layers) * 0.75

)

for layer in backbone.layers[:freeze_until]:

    layer.trainable = False

for layer in backbone.layers[freeze_until:]:

    layer.trainable = True

model.compile(

    optimizer=tf.keras.optimizers.Adam(

        learning_rate=1e-5

    ),

    loss="sparse_categorical_crossentropy",

    metrics=["accuracy"]

)

history_phase2 = model.fit(

    train_dataset,

    validation_data=validation_dataset,

    initial_epoch=history_phase1.epoch[-1] + 1,

    epochs=35,

    callbacks=callbacks

)

print()
print("="*60)
print("ENTRENAMIENTO FINALIZADO")
print("="*60)

# ==========================================================
# Historial completo
# ==========================================================

history = {}

for key in history_phase1.history.keys():

    history[key] = (

        history_phase1.history[key]

        +

        history_phase2.history[key]

    )

print()

print("Épocas totales:", len(history["loss"]))

print("✔ Historial unificado.")

# ==========================================================
# MÓDULO 10
# Cargar modelo y etiquetas
# ==========================================================

import json
import numpy as np
import tensorflow as tf

from pathlib import Path

MODEL_PATH = CHECKPOINT_DIR / "best_model.keras"
LABELS_PATH = OUTPUT_DIR / "labels.json"

print("=" * 60)
print("CARGANDO MODELO")
print("=" * 60)

model = tf.keras.models.load_model(MODEL_PATH)

with open(LABELS_PATH, "r", encoding="utf-8") as f:
    labels = json.load(f)

# labels.json puede ser lista o diccionario
if isinstance(labels, list):
    CLASS_NAMES = labels
else:
    CLASS_NAMES = [labels[str(i)] for i in range(len(labels))]

print("Modelo cargado correctamente.")
print("Número de clases:", len(CLASS_NAMES))

print("=" * 60)

# ==========================================================
# Función de predicción
# ==========================================================

import cv2

def predict_image(image_path, top_k=5):

    image = cv2.imread(str(image_path), cv2.IMREAD_GRAYSCALE)

    if image is None:
        raise FileNotFoundError(image_path)

    image = cv2.resize(image, IMAGE_SIZE)

    image = image.astype(np.float32) / 255.0

    image = np.stack([image, image, image], axis=-1)

    image = np.expand_dims(image, axis=0)

    prediction = model.predict(image, verbose=0)[0]

    top_indices = np.argsort(prediction)[::-1][:top_k]

    print("=" * 60)
    print("PREDICCIÓN")
    print("=" * 60)

    for idx in top_indices:

        print(

            f"{CLASS_NAMES[idx]:<8}"

            f"{prediction[idx]*100:6.2f}%"

        )

    return prediction

# Obtener el orden REAL utilizado por TensorFlow
raw_dataset = tf.keras.utils.image_dataset_from_directory(
    IMAGES_DIR,
    labels="inferred",
    label_mode="int",
    color_mode="grayscale",
    image_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=False
)

CLASS_NAMES = raw_dataset.class_names

print("CLASS_NAMES actualizadas correctamente.")

import json

with open(OUTPUT_DIR / "labels.json", "w", encoding="utf-8") as f:
    json.dump(CLASS_NAMES, f, ensure_ascii=False, indent=4)

print("labels.json actualizado.")

# Crear un diccionario desde CHARACTERS
character_map = {
    c.hanzi: {
        "hanzi": c.hanzi,
        "pinyin": c.pinyin,
        "spanish": c.spanish
    }
    for c in CHARACTERS
}

metadata = []

for idx, hanzi in enumerate(CLASS_NAMES):
    item = character_map[hanzi].copy()
    item["index"] = idx
    metadata.append(item)

with open(OUTPUT_DIR / "metadata.json", "w", encoding="utf-8") as f:
    json.dump(metadata, f, ensure_ascii=False, indent=4)

print("metadata.json actualizado.")

# ==========================================================
# Elegir una imagen aleatoria
# ==========================================================

import random

character = random.choice(CHARACTERS)

folder = IMAGES_DIR / character.hanzi

image_path = random.choice(list(folder.glob("*.png")))

print(image_path)
import matplotlib.pyplot as plt

img = cv2.imread(

    str(image_path),

    cv2.IMREAD_GRAYSCALE

)

plt.figure(figsize=(5,5))

plt.imshow(img, cmap="gray")

plt.title("Imagen de prueba")

plt.axis("off")

plt.show()
prediction = predict_image(image_path)

# ==========================================================
# VALIDACIÓN FINAL ANTES DE EXPORTAR MODELO
# ==========================================================

import json
import numpy as np
import tensorflow as tf
import random
import matplotlib.pyplot as plt
from pathlib import Path

print("="*60)
print("VALIDACIÓN FINAL DEL MODELO")
print("="*60)

# ==========================================================
# 1. RECONSTRUIR ORDEN REAL DE TENSORFLOW
# ==========================================================

raw_dataset = tf.keras.utils.image_dataset_from_directory(
    IMAGES_DIR,
    labels="inferred",
    label_mode="int",
    color_mode="grayscale",
    image_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=False
)

REAL_CLASS_NAMES = raw_dataset.class_names

print("\n✔ Orden TensorFlow cargado")
print("Total clases:", len(REAL_CLASS_NAMES))

# ==========================================================
# 2. CARGAR LABELS EXPORTADOS
# ==========================================================

with open(OUTPUT_DIR / "labels.json", "r", encoding="utf-8") as f:
    EXPORTED_LABELS = json.load(f)

print("\n✔ labels.json cargado")

# ==========================================================
# 3. VERIFICAR CONSISTENCIA
# ==========================================================

mismatch = False

for i in range(len(REAL_CLASS_NAMES)):
    if REAL_CLASS_NAMES[i] != EXPORTED_LABELS[i]:
        print(f"❌ Desajuste en índice {i}")
        print("TensorFlow:", REAL_CLASS_NAMES[i])
        print("Exportado :", EXPORTED_LABELS[i])
        mismatch = True

if not mismatch:
    print("\n✔ labels.json coincide con TensorFlow")

# ==========================================================
# 4. PRUEBA DE PREDICCIÓN REAL
# ==========================================================

model = tf.keras.models.load_model(CHECKPOINT_DIR / "best_model.keras")

idx = random.randint(0, len(REAL_CLASS_NAMES) - 1)
class_name = REAL_CLASS_NAMES[idx]

img_path = list((IMAGES_DIR / class_name).glob("*.png"))[0]

img = tf.keras.utils.load_img(
    img_path,
    color_mode="grayscale",
    target_size=IMAGE_SIZE
)

img_array = tf.keras.utils.img_to_array(img)
img_array = img_array / 255.0
# Convertir a Tensor antes de aplicar tf.image.grayscale_to_rgb
img_array = tf.convert_to_tensor(img_array)
img_array = tf.image.grayscale_to_rgb(img_array)
img_array = tf.expand_dims(img_array, 0)

prediction = model.predict(img_array, verbose=0)[0]
pred_idx = np.argmax(prediction)

print("\n✔ PRUEBA DE PREDICCIÓN")
print("Real       :", class_name)
print("Predicción :", REAL_CLASS_NAMES[pred_idx])
print("Confianza  :", float(np.max(prediction)))

# ==========================================================
# 5. VISUALIZACIÓN
# ==========================================================

plt.figure(figsize=(4,4))
plt.imshow(img, cmap="gray")
plt.title(f"Real: {class_name} | Pred: {REAL_CLASS_NAMES[pred_idx]}")
plt.axis("off")
plt.show()

# ==========================================================
# RESULTADO FINAL
# ==========================================================

print("\n" + "="*60)

if not mismatch:
    print("TODO CORRECTO")
else:
    print("ERROR EN LABELS")

print("="*60)

!find / -name 'chinoV2.ipynb'